# CI para FastAPI con pytest
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn requests
      - name: Iniciar FastAPI en segundo plano
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 3
      - name: Ejecutar pruebas
        run: |
          python tests/test_counter_service.py
